sonar.organization=iamy0uu
sonar.projectKey=IamY0uu_timofx
sonar.projectName=Timo Backend
sonar.sources=src
sonar.exclusions=node_modules/**,prisma/migrations/**,**/*.test.js
sonar.language=js
sonar.sourceEncoding=UTF-8
